### ISSUE TITLE
Away mode and zones

### ISSUE THREAD

**Issue by pdemarco925** [deHugo/icomfort-js#6]
Dan,
Three questions.

First, did Lennox change something recently? I'm getting an error ("missing value for parameter: 'authorizationToken") when trying to use the setProgramMode (even in your tests). I know it used to work.

Second, do you know, if I wanted to set the thermostat to away mode. Is just using the setThermostatInfo(data) method and setting "Away_Mode"= 1 sufficient, or is there some additional logic required (either using the setProgramMode(data)) method or something else not currently supported?

Third, related to zones. Someone asked if I could extend my project (homebridge-icomfort) to support zones. I had them run your test suite and their returned data can be seen here: https://github.com/pdemarco925/homebridge-icomfort/issues/1 
Their system has 4 zones, and the thermostat info for the zones looks like a set of data vectors. How does your code handle this? In other words, looking at your example code for using the setThermostatInfo(data) how does your code distinguish the multiple instances of Cool_Set_Point for each zone returned? Is it just something like this? Cool_Set_Point[2]: currentSettings.Cool_Set_Point+2?

Thanks!

**Comment by danielmcq** [comment]
@pdemarco925 I noticed that first problem a week or two ago. It seems they require a token to use the endpoints which the iComfort website uses. I've discovered that the value of that token is simply the username encoded using base64. The problem is they can easily change how that token is generated. It's not ideal to keep using these endpoints which seem to be designed specifically which a webpage in mind. I believe we can get all of the same functionality out of their endpoints that are used by the mobile app. Therefore, in the next version (2.x), I will be removing the `setProgramMode` method, since it relies on that endpoint which requires the *authorizationToken*.

For the second question, I believe that as you suggest, setting the *Away_Mode* to *1* should be sufficient. The `setThermostatInfo` method should work for that. However, I will research this some more. I need to capture the data moving between the iOS app and their servers to be sure. I'll update with another comment on this issue a little later.

For the third question, this is new territory. My home was only configured with one zone, but I had hoped someone trying to use this code who has more than one zone would show up sooner than later. It seems that to update settings for a zone, the `setThermostatInfo` endpoint should be used. I believe you would specify the zone number in the payload. However, I'm not certain about this. I will look into what it takes to configure my home with multiple zones (it may not be possible without additional hardware). If I can get my system running with more than one zone, then I might be able to better verify how updates to the various zones is supposed to work.

**Comment by danielmcq** [comment]
I found out that there’s another endpoint used specifically for setting away mode. I’ll get that added to the current version. 

I spent some time trying to see if I could get the `setProgramMode` test to work by adding the authorization token, but it looks like it won’t be possible without authenticating a session through their web page.

**Comment by pdemarco925** [comment]
Think I confirmed you can't use setThermostatInfo to set to away mode, so will definitely need the new endpoint. 

I'm going to pull the setProgramMode from my code and just deal with manual mode configurations. As you get around to working on the next version with the mobile app endpoints, let me know if you need any help testing things out. I'll definitely want to update my code to align with your newer version.

As for zones. Same problem here. I only have a single zone system myself, so makes it difficult to test things out.

**Comment by danielmcq** [comment]
@pdemarco925 I just published version 1.3.0 with PR #7. It has a method named `setAwayMode` which will allow the away mode to be activated or deactivated. I added it to the README as well. I think this will take care of the away mode concern for now. 

Thank you for your offer to help on the testing. I believe in the next week or two I'll have betas/release candidates for version 2.0.0. I'll tag you on the updates so you can test things out.

**Comment by pdemarco925** [comment]
Thanks. Works great.
